### ISSUE TITLE
Use build strings instead of features

### ISSUE THREAD

**Issue by minrk** [conda-forge/blas-feedstock#11]
Features in conda seem to behave in surprising ways, and it seems that in general they ought to be avoided and are not a good fit for implementing variants. From [other discussions on features](https://github.com/conda-forge/staged-recipes/pull/1501#issuecomment-280815551):

> it is very important that packages with track_features obey two rules:
>
> - such packages are never listed in the depends field of any other package; and
> - there are not other versions of the package without the track_features entry

The current blas-feature implementation in conda-forge violates the first rule by packages such as numpy depending directly on the `blas` metapackage. The main negative consequence of this is that it gives the conda solver the opportunity to minimize features by removing both the package and the metapackage and choosing an alternate version of the package that has no features. The most common example I encounter (and I do encounter it regularly) is https://github.com/conda/conda/issues/6065 where implicitly-installed numpy will be the no-feature mkl version from defaults, despite explicitly requesting conda-forge packages:

```
$ conda create --dry-run -n ignore -c conda-forge boost=1.65.1 python=3.6
The following NEW packages will be INSTALLED:

    boost:           1.65.1-py36_0         conda-forge
    boost-cpp:       1.65.1-1              conda-forge
    bzip2:           1.0.6-1               conda-forge
    ca-certificates: 2018.1.18-0           conda-forge
    certifi:         2018.1.18-py36_0      conda-forge
    icu:             58.2-0                conda-forge
    intel-openmp:    2018.0.0-h8158457_8   defaults
    libgfortran:     3.0.1-h93005f0_2      defaults
    mkl:             2018.0.1-hfbd8650_4   defaults
    ncurses:         5.9-10                conda-forge
    numpy:           1.14.1-py36ha726252_2 defaults
    openssl:         1.0.2n-0              conda-forge
    pip:             9.0.1-py36_1          conda-forge
    python:          3.6.4-0               conda-forge
    ...
```

It seems that switching the blas-selection process to use build strings instead of features would result in more expected behavior than the current features, which often have the perverse result of deprioritizing conda-forge packages that have features. In the [mpi metapackage](https://github.com/conda-forge/staged-recipes/pull/1501) we have the following behavior:

1. mpi mpkg is empty has a build string for each provider (all the same version to avoid expressing preference)
2. mpi 'providers' (mpich, openmpi) depend directly on mpi mpkg with appropriate build string, thus enforcing mutual exclusivity
3. downstream packages depend directly on their chosen providers, no need to depend on mpkg

I think this approach ought to work well for blas:

1. blas 2.x has build strings for openblas, noblas (keep existing minor-version preference)
2. openblas depends on blas 2.x openblas
3. numpy depends directly on openblas, not blas
4. no features or tracking anywhere

**Comment by ocefpaf** [comment]
@isuruf I'd love to hear your opinion on this one and, if you agree, merge it :wink:

**Comment by msarahan** [comment]
This is pretty much how we do it in defaults. blas``-devel`` packages use run_exports to add their runtime, but we attach the blas metapackage dependency to the thing being built (i.e. numpy):

https://github.com/AnacondaRecipes/numpy-feedstock/blob/master/recipe/meta.yaml#L58
https://github.com/AnacondaRecipes/openblas-feedstock/blob/master/recipe/meta.yaml#L98

We do not attach the blas metapackage dep to the runtime library because we thought there may be instances where people have use cases of having both mkl and openblas in an env, but only one being used by a given process at a time.

People must select their metapackage with something like

```
conda install numpy blas=*=openblas
```

@jjhelmus has a good scheme of using the version number to establish priority when no build string is specified.  For him, it's tensorflow, and he has eigen, mkl, and gpu builds.  He would have something like:

tf-3.0-eigen
tf-2.0-mkl
tf-1.0-gpu

Here the critical thing is just that the most compatible version, eigen, is the one that gets chosen when the user does not specify any kind of ``tf=*=something`` expression.

**Comment by isuruf** [comment]
Done in #16
