### ISSUE TITLE
More variants in conda-forge

### ISSUE THREAD

**Issue by isuruf** [conda-forge/blas-feedstock#6]
There are more variants in conda-forge.

- https://github.com/conda-forge/lapack-feedstock
- https://github.com/conda-forge/clapack-feedstock

**Comment by isuruf** [comment]
`lapack-feedstock` should probably be renamed to `netlib-lapack-feedstock`

**Comment by jakirkham** [comment]
Indeed. Time to update things. Will need to bump BLAS to `2.x` in order to handle this. Also we have to decide on the ordering of these. Personally I would like to keep `openblas` as highest priority as it is the most performant BLAS. Have no real preference how the other 2 are ordered. Last would still be `noblas`. This will also require a rebuild of all BLAS dependent packages to really take advantage of these option.

**Comment by jakirkham** [comment]
cc @conda-forge/lapack @conda-forge/clapack

**Comment by isuruf** [comment]
Done in #16
